name: FlaskCI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
    
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.x
    
          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
    
          - name: Run Tests
            run: |
              python -m unittest discover tests
    deploy:
        runs-on: ubuntu-latest

        needs: test
        if: github.event_name == 'push' && github.event_name != 'pull_request' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.x

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Deploy to Server
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
                ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-3-137-151-215.us-east-2.compute.amazonaws.com "cd ~/6156-ItemService && git pull"
            
            - name: Stop Previous App
              run: |
                PID=$(pgrep -f "python app.py")

                if [ -n "$PID" ]; then
                  echo "Killing previous process with PID $PID"
                  kill $PID
                else
                  echo "No previous process"
                fi
        
            - name: Start New App
              run: |
                nohup python app.py &